# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40c0c8d5abaf0a584d0ec5d44c7e4869705fb87754b0c41d547ed30cb12b21dc1be03189f2060f3bd42727103185740eac101b81d7acd8bd7ec93b31f53113c7

test:
  secret_key_base: 1386bf06a2abf2b3ff497bec651d240a401c45aaaf4bbdc15f76a7d43a0d933880bb760b225a0d6c4beb34a89602457e58c7ca404eb645e791230b78a4991e55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
